#!/bin/bash

echo "Aguarde, o Sonic ISP, Sera atualizado"
echo ""
echo "Se conentando com www.sonicisp.com.br"
echo ""
echo " ########################################################## "
cd /var/www/
wget http://update.sonicisp.com.br/linux-packages/update.tar.gz
tar zxf update.tar.gz
mysql -uroot -p33#erp@myrouter#33 sonic < UPDATE.sql
rm update.tar.gz
echo ""
echo "Sistema web atualizado"
echo ""
echo "Procurando atulizacoes binarias"
cd /bin
wget http://update.sonicisp.com.br/linux-packages/extra.tar.gz
tar zxf extra.tar.gz
rm extra.tar.gz
sudo chmod a+x extra
sudo chmod 777 extra
sudo extra

echo "############################################"
echo "############################################"
echo " "
echo "               Sistema atualizado           "
echo " "
echo "############################################"
echo "############################################"
